### ISSUE TITLE
cfn2py SyntaxError with missing parentheses

### ISSUE THREAD

**Issue by Marakai** [cloudtools/troposphere#1359]
`cfn2py` in `troposphere` version 2.4.6 is failing with 

` File "/usr/bin/cfn2py", line 52
    print 'from troposphere import Base64, Select, FindInMap, GetAtt, GetAZs, Join, Output, If, And, Not, Or, Equals, Condition'
                                                                                                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('from troposphere import Base64, Select, FindInMap, GetAtt, GetAZs, Join, Output, If, And, Not, Or, Equals, Condition')?`

At first I thought it may still be a Python2 script, but right at the top it says

`#!/usr/bin/python3.6`

**Comment by markpeek** [comment]
That's really odd as the code in github [shows](https://github.com/cloudtools/troposphere/blob/master/scripts/cfn2py#L1):
`#!/usr/bin/env python` at the top. But it is a Python 2 script (I know, I know...get with Python 3 :-) ) but you can always run 2to3 on it to run under Python 3.

**Comment by Marakai** [comment]
How bizarre. Did PyPi somehow get out of sync? I made sure to run pip with -U.

**Comment by allyunion** [comment]
I noticed a lot of the print statements still using the Python 2 style.  I have submitted a pull request and added the print_function from __future__ 

https://github.com/cloudtools/troposphere/pull/1364

**Comment by allyunion** [comment]
This should be fixed now

**Comment by Marakai** [comment]
I see that the master branch has version 2.4.6 and cfn2py looks fixed. But I have version 2.4.6 from pypi and the script in /usr/bin is still wrong.

I forced a start-over:

```
$ sudo pip3 uninstall troposphere
Uninstalling troposphere-2.4.6:
  Would remove:
    /usr/bin/cfn
    /usr/bin/cfn2py
    /usr/lib/python3.6/site-packages/troposphere-2.4.6.dist-info/*
    /usr/lib/python3.6/site-packages/troposphere/*
Proceed (y/n)? y
  Successfully uninstalled troposphere-2.4.6
$ sudo pip3 install -U troposphere
Collecting troposphere
Requirement already satisfied, skipping upgrade: cfn-flip>=1.0.2 in /usr/lib/python3.6/site-packages (from troposphere) (1.0.3)
Requirement already satisfied, skipping upgrade: Click in /usr/lib64/python3.6/site-packages (from cfn-flip>=1.0.2->troposphere) (7.0)
Requirement already satisfied, skipping upgrade: PyYAML in /usr/lib64/python3.6/site-packages (from cfn-flip>=1.0.2->troposphere) (5.1)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3.6/site-packages (from cfn-flip>=1.0.2->troposphere) (1.11.0)
Installing collected packages: troposphere
Successfully installed troposphere-2.4.6
```

then I look at `/usr/bin/cfn2py` - and nope, it's still the old one! Some version confusion on pypi?

**Comment by Marakai** [comment]
Update:

I cloned the repo, then did

```
$ sudo pip3 uninstall troposphere
$ python3 setup.py sdist
$ sudo pip3 install dist/troposphere-2.4.6.tar.gz
```

and this same version number package now has the correct `cfn2py` script (and it looks like some other fixes too!). Should the version actually say 2.4.7 which is why pypi didn't pick up the fixes?

**Comment by markpeek** [comment]
Just release 2.4.7 which has the latest cfn2py script.
