### ISSUE TITLE
RDS read replica ValueError

### ISSUE THREAD

**Issue by alwaysanirudh** [cloudtools/troposphere#197]
Hi,

I'm trying to a create a RDS read replica Cloudfront script using troposhere. According to CF documentation I have to pass the master DB identifier as REF for the replica DB   SourceDBInstanceIdentifier. But when I try to do it is throws an error as follows. 
```ValueError: Resource Engine required in type AWS::RDS::DBInstance```

You can refer my code snippet:

```
dbMaster = template.add_resource(DBInstance("DBMaster",
                                                              DBName='anirudh',
                                                              AllocatedStorage="5",
                                                              DBInstanceIdentifier = "anirudhMaster",
                                                              DBInstanceClass="db.t1.micro",
                                                              Engine="MySQL",
                                                              MasterUsername='root',
                                                              MasterUserPassword='root'
                                                              )
                                                   )

dbSlave = template.add_resource(DBInstance( "DBSlave",
                                                                 SourceDBInstanceIdentifier=Ref(dbMaster),
                                                                 DBInstanceClass="db.t1.micro",
                                                                 )
                                                      )

```

**Comment by markpeek** [comment]
The documentation is not clear about whether Engine is required when specifying a SourceDBInstanceIdentifier. You could try either adding Engine="MySQL" to the DBSlave object or change the required setting for Engine from True to False inside the troposphere/rds.py source file. Let me know if that latter one works.

I'll leave this open to follow up later by getting clarification on the documentation.

**Comment by alwaysanirudh** [comment]
As far as AWS documentation is concerned. For read replica all you need is SourceDBInstanceIdentifier and DBInstanceClass. [See Here](https://s3-us-west-2.amazonaws.com/cloudformation-templates-us-west-2/RDS_MySQL_With_Read_Replica.template)

In Troposhere package there few parameters which are defined as required in validation (That's absolutely fine for the master DB) but when SourceDBInstanceIdentifier is defined you don't require the validations. The fields you need to handle is:
AllocatedStorage
Engine
MasterUsername
MasterUserPassword

**Comment by markpeek** [comment]
@alwaysanirudh I just pushed a change onto a testing branch which should provide better error checking and allow for the read replica use case. If you have time please let me know if this works for you.

**Comment by alwaysanirudh** [comment]
@markpeek This works fine now. You can merge it. :+1:

**Comment by Snedden** [comment]
Does this work? I seem to have the same issue where I provide the DBInstanceIdentifier but I still get a similar error saying : 

Resource Engine is required in type AWS::RDS::DBInstance
